/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ProjectInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addDonor"
      | "admin"
      | "createMilestone"
      | "donorCount"
      | "hasVoted"
      | "isDonor"
      | "milestoneProofs"
      | "milestones"
      | "organizer"
      | "submitProof"
      | "title"
      | "voteOnProof"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DonorAdded"
      | "MilestoneApproved"
      | "MilestoneCreated"
      | "MilestoneRejected"
      | "ProofSubmitted"
      | "VoteCast"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addDonor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createMilestone",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "donorCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDonor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "milestoneProofs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "milestones",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "organizer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "submitProof",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(functionFragment: "title", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "voteOnProof",
    values: [BigNumberish, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "addDonor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donorCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isDonor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "milestoneProofs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "milestones", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "organizer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "title", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "voteOnProof",
    data: BytesLike
  ): Result;
}

export namespace DonorAddedEvent {
  export type InputTuple = [donor: AddressLike];
  export type OutputTuple = [donor: string];
  export interface OutputObject {
    donor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneApprovedEvent {
  export type InputTuple = [milestoneId: BigNumberish];
  export type OutputTuple = [milestoneId: bigint];
  export interface OutputObject {
    milestoneId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneCreatedEvent {
  export type InputTuple = [
    milestoneId: BigNumberish,
    description: string,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    milestoneId: bigint,
    description: string,
    amount: bigint
  ];
  export interface OutputObject {
    milestoneId: bigint;
    description: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneRejectedEvent {
  export type InputTuple = [milestoneId: BigNumberish];
  export type OutputTuple = [milestoneId: bigint];
  export interface OutputObject {
    milestoneId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofSubmittedEvent {
  export type InputTuple = [
    milestoneId: BigNumberish,
    ipfsHash: string,
    submitter: AddressLike
  ];
  export type OutputTuple = [
    milestoneId: bigint,
    ipfsHash: string,
    submitter: string
  ];
  export interface OutputObject {
    milestoneId: bigint;
    ipfsHash: string;
    submitter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    milestoneId: BigNumberish,
    voter: AddressLike,
    approve: boolean
  ];
  export type OutputTuple = [
    milestoneId: bigint,
    voter: string,
    approve: boolean
  ];
  export interface OutputObject {
    milestoneId: bigint;
    voter: string;
    approve: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Project extends BaseContract {
  connect(runner?: ContractRunner | null): Project;
  waitForDeployment(): Promise<this>;

  interface: ProjectInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addDonor: TypedContractMethod<[_donor: AddressLike], [void], "nonpayable">;

  admin: TypedContractMethod<[], [string], "view">;

  createMilestone: TypedContractMethod<
    [_description: string, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  donorCount: TypedContractMethod<[], [bigint], "view">;

  hasVoted: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isDonor: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  milestoneProofs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        ipfsHash: string;
        timestamp: bigint;
        location: string;
        submitter: string;
      }
    ],
    "view"
  >;

  milestones: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean, boolean, bigint, bigint] & {
        description: string;
        amount: bigint;
        isCompleted: boolean;
        isApproved: boolean;
        approvalCount: bigint;
        rejectionCount: bigint;
      }
    ],
    "view"
  >;

  organizer: TypedContractMethod<[], [string], "view">;

  submitProof: TypedContractMethod<
    [_milestoneId: BigNumberish, _ipfsHash: string, _location: string],
    [void],
    "nonpayable"
  >;

  title: TypedContractMethod<[], [string], "view">;

  voteOnProof: TypedContractMethod<
    [_milestoneId: BigNumberish, _approve: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addDonor"
  ): TypedContractMethod<[_donor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createMilestone"
  ): TypedContractMethod<
    [_description: string, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "donorCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isDonor"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "milestoneProofs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        ipfsHash: string;
        timestamp: bigint;
        location: string;
        submitter: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "milestones"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean, boolean, bigint, bigint] & {
        description: string;
        amount: bigint;
        isCompleted: boolean;
        isApproved: boolean;
        approvalCount: bigint;
        rejectionCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "organizer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "submitProof"
  ): TypedContractMethod<
    [_milestoneId: BigNumberish, _ipfsHash: string, _location: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "title"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "voteOnProof"
  ): TypedContractMethod<
    [_milestoneId: BigNumberish, _approve: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DonorAdded"
  ): TypedContractEvent<
    DonorAddedEvent.InputTuple,
    DonorAddedEvent.OutputTuple,
    DonorAddedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneApproved"
  ): TypedContractEvent<
    MilestoneApprovedEvent.InputTuple,
    MilestoneApprovedEvent.OutputTuple,
    MilestoneApprovedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneCreated"
  ): TypedContractEvent<
    MilestoneCreatedEvent.InputTuple,
    MilestoneCreatedEvent.OutputTuple,
    MilestoneCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneRejected"
  ): TypedContractEvent<
    MilestoneRejectedEvent.InputTuple,
    MilestoneRejectedEvent.OutputTuple,
    MilestoneRejectedEvent.OutputObject
  >;
  getEvent(
    key: "ProofSubmitted"
  ): TypedContractEvent<
    ProofSubmittedEvent.InputTuple,
    ProofSubmittedEvent.OutputTuple,
    ProofSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "DonorAdded(address)": TypedContractEvent<
      DonorAddedEvent.InputTuple,
      DonorAddedEvent.OutputTuple,
      DonorAddedEvent.OutputObject
    >;
    DonorAdded: TypedContractEvent<
      DonorAddedEvent.InputTuple,
      DonorAddedEvent.OutputTuple,
      DonorAddedEvent.OutputObject
    >;

    "MilestoneApproved(uint256)": TypedContractEvent<
      MilestoneApprovedEvent.InputTuple,
      MilestoneApprovedEvent.OutputTuple,
      MilestoneApprovedEvent.OutputObject
    >;
    MilestoneApproved: TypedContractEvent<
      MilestoneApprovedEvent.InputTuple,
      MilestoneApprovedEvent.OutputTuple,
      MilestoneApprovedEvent.OutputObject
    >;

    "MilestoneCreated(uint256,string,uint256)": TypedContractEvent<
      MilestoneCreatedEvent.InputTuple,
      MilestoneCreatedEvent.OutputTuple,
      MilestoneCreatedEvent.OutputObject
    >;
    MilestoneCreated: TypedContractEvent<
      MilestoneCreatedEvent.InputTuple,
      MilestoneCreatedEvent.OutputTuple,
      MilestoneCreatedEvent.OutputObject
    >;

    "MilestoneRejected(uint256)": TypedContractEvent<
      MilestoneRejectedEvent.InputTuple,
      MilestoneRejectedEvent.OutputTuple,
      MilestoneRejectedEvent.OutputObject
    >;
    MilestoneRejected: TypedContractEvent<
      MilestoneRejectedEvent.InputTuple,
      MilestoneRejectedEvent.OutputTuple,
      MilestoneRejectedEvent.OutputObject
    >;

    "ProofSubmitted(uint256,string,address)": TypedContractEvent<
      ProofSubmittedEvent.InputTuple,
      ProofSubmittedEvent.OutputTuple,
      ProofSubmittedEvent.OutputObject
    >;
    ProofSubmitted: TypedContractEvent<
      ProofSubmittedEvent.InputTuple,
      ProofSubmittedEvent.OutputTuple,
      ProofSubmittedEvent.OutputObject
    >;

    "VoteCast(uint256,address,bool)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
