/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ProjectInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addDonor"
      | "addVerifier"
      | "admin"
      | "createMilestone"
      | "createdAt"
      | "description"
      | "donorCount"
      | "fundingGoal"
      | "getMilestone"
      | "getMilestoneCount"
      | "getProof"
      | "hasUserVoted"
      | "hasVoted"
      | "isDonor"
      | "isVerifier"
      | "milestoneProofs"
      | "milestones"
      | "organizer"
      | "removeVerifier"
      | "submitProof"
      | "title"
      | "verifierCount"
      | "voteOnProof"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DonorAdded"
      | "MilestoneApproved"
      | "MilestoneCreated"
      | "MilestoneRejected"
      | "ProofSubmitted"
      | "VerifierAdded"
      | "VerifierRemoved"
      | "VoteCast"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addDonor",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createMilestone",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "createdAt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "description",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "donorCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fundingGoal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMilestone",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMilestoneCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProof",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasUserVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDonor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "milestoneProofs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "milestones",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "organizer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitProof",
    values: [BigNumberish, BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "title", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifierCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "voteOnProof",
    values: [BigNumberish, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "addDonor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createdAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "description",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donorCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundingGoal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMilestoneCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProof", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasUserVoted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isDonor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isVerifier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "milestoneProofs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "milestones", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "organizer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "title", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifierCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteOnProof",
    data: BytesLike
  ): Result;
}

export namespace DonorAddedEvent {
  export type InputTuple = [donor: AddressLike, amount: BigNumberish];
  export type OutputTuple = [donor: string, amount: bigint];
  export interface OutputObject {
    donor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneApprovedEvent {
  export type InputTuple = [
    milestoneId: BigNumberish,
    approvalCount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    milestoneId: bigint,
    approvalCount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    milestoneId: bigint;
    approvalCount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneCreatedEvent {
  export type InputTuple = [
    milestoneId: BigNumberish,
    title: string,
    description: string,
    requiredApprovals: BigNumberish
  ];
  export type OutputTuple = [
    milestoneId: bigint,
    title: string,
    description: string,
    requiredApprovals: bigint
  ];
  export interface OutputObject {
    milestoneId: bigint;
    title: string;
    description: string;
    requiredApprovals: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneRejectedEvent {
  export type InputTuple = [
    milestoneId: BigNumberish,
    rejectionCount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    milestoneId: bigint,
    rejectionCount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    milestoneId: bigint;
    rejectionCount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofSubmittedEvent {
  export type InputTuple = [
    milestoneId: BigNumberish,
    beforeImageHash: BytesLike,
    afterImageHash: BytesLike,
    gpsCoordinates: string,
    submitter: AddressLike
  ];
  export type OutputTuple = [
    milestoneId: bigint,
    beforeImageHash: string,
    afterImageHash: string,
    gpsCoordinates: string,
    submitter: string
  ];
  export interface OutputObject {
    milestoneId: bigint;
    beforeImageHash: string;
    afterImageHash: string;
    gpsCoordinates: string;
    submitter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierAddedEvent {
  export type InputTuple = [verifier: AddressLike];
  export type OutputTuple = [verifier: string];
  export interface OutputObject {
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierRemovedEvent {
  export type InputTuple = [verifier: AddressLike];
  export type OutputTuple = [verifier: string];
  export interface OutputObject {
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    milestoneId: BigNumberish,
    voter: AddressLike,
    approve: boolean,
    comment: string
  ];
  export type OutputTuple = [
    milestoneId: bigint,
    voter: string,
    approve: boolean,
    comment: string
  ];
  export interface OutputObject {
    milestoneId: bigint;
    voter: string;
    approve: boolean;
    comment: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Project extends BaseContract {
  connect(runner?: ContractRunner | null): Project;
  waitForDeployment(): Promise<this>;

  interface: ProjectInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addDonor: TypedContractMethod<
    [_donor: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  addVerifier: TypedContractMethod<
    [_verifier: AddressLike],
    [void],
    "nonpayable"
  >;

  admin: TypedContractMethod<[], [string], "view">;

  createMilestone: TypedContractMethod<
    [_title: string, _description: string, _requiredApprovals: BigNumberish],
    [void],
    "nonpayable"
  >;

  createdAt: TypedContractMethod<[], [bigint], "view">;

  description: TypedContractMethod<[], [string], "view">;

  donorCount: TypedContractMethod<[], [bigint], "view">;

  fundingGoal: TypedContractMethod<[], [bigint], "view">;

  getMilestone: TypedContractMethod<
    [_milestoneId: BigNumberish],
    [
      [string, string, bigint, boolean, boolean, bigint, bigint] & {
        _title: string;
        _description: string;
        _requiredApprovals: bigint;
        _isCompleted: boolean;
        _isApproved: boolean;
        _approvalCount: bigint;
        _rejectionCount: bigint;
      }
    ],
    "view"
  >;

  getMilestoneCount: TypedContractMethod<[], [bigint], "view">;

  getProof: TypedContractMethod<
    [_milestoneId: BigNumberish],
    [
      [string, string, string, bigint, string, bigint] & {
        _beforeImageHash: string;
        _afterImageHash: string;
        _gpsCoordinates: string;
        _timestamp: bigint;
        _submitter: string;
        _status: bigint;
      }
    ],
    "view"
  >;

  hasUserVoted: TypedContractMethod<
    [_milestoneId: BigNumberish, _user: AddressLike],
    [boolean],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isDonor: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isVerifier: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  milestoneProofs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, string, bigint] & {
        beforeImageHash: string;
        afterImageHash: string;
        gpsCoordinates: string;
        timestamp: bigint;
        submitter: string;
        status: bigint;
      }
    ],
    "view"
  >;

  milestones: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean, boolean, bigint, bigint, bigint] & {
        title: string;
        description: string;
        requiredApprovals: bigint;
        isCompleted: boolean;
        isApproved: boolean;
        approvalCount: bigint;
        rejectionCount: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  organizer: TypedContractMethod<[], [string], "view">;

  removeVerifier: TypedContractMethod<
    [_verifier: AddressLike],
    [void],
    "nonpayable"
  >;

  submitProof: TypedContractMethod<
    [
      _milestoneId: BigNumberish,
      _beforeImageHash: BytesLike,
      _afterImageHash: BytesLike,
      _gpsCoordinates: string
    ],
    [void],
    "nonpayable"
  >;

  title: TypedContractMethod<[], [string], "view">;

  verifierCount: TypedContractMethod<[], [bigint], "view">;

  voteOnProof: TypedContractMethod<
    [_milestoneId: BigNumberish, _approve: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addDonor"
  ): TypedContractMethod<
    [_donor: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addVerifier"
  ): TypedContractMethod<[_verifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createMilestone"
  ): TypedContractMethod<
    [_title: string, _description: string, _requiredApprovals: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createdAt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "description"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "donorCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fundingGoal"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMilestone"
  ): TypedContractMethod<
    [_milestoneId: BigNumberish],
    [
      [string, string, bigint, boolean, boolean, bigint, bigint] & {
        _title: string;
        _description: string;
        _requiredApprovals: bigint;
        _isCompleted: boolean;
        _isApproved: boolean;
        _approvalCount: bigint;
        _rejectionCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMilestoneCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProof"
  ): TypedContractMethod<
    [_milestoneId: BigNumberish],
    [
      [string, string, string, bigint, string, bigint] & {
        _beforeImageHash: string;
        _afterImageHash: string;
        _gpsCoordinates: string;
        _timestamp: bigint;
        _submitter: string;
        _status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasUserVoted"
  ): TypedContractMethod<
    [_milestoneId: BigNumberish, _user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isDonor"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isVerifier"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "milestoneProofs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, string, bigint] & {
        beforeImageHash: string;
        afterImageHash: string;
        gpsCoordinates: string;
        timestamp: bigint;
        submitter: string;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "milestones"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean, boolean, bigint, bigint, bigint] & {
        title: string;
        description: string;
        requiredApprovals: bigint;
        isCompleted: boolean;
        isApproved: boolean;
        approvalCount: bigint;
        rejectionCount: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "organizer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeVerifier"
  ): TypedContractMethod<[_verifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitProof"
  ): TypedContractMethod<
    [
      _milestoneId: BigNumberish,
      _beforeImageHash: BytesLike,
      _afterImageHash: BytesLike,
      _gpsCoordinates: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "title"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifierCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "voteOnProof"
  ): TypedContractMethod<
    [_milestoneId: BigNumberish, _approve: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DonorAdded"
  ): TypedContractEvent<
    DonorAddedEvent.InputTuple,
    DonorAddedEvent.OutputTuple,
    DonorAddedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneApproved"
  ): TypedContractEvent<
    MilestoneApprovedEvent.InputTuple,
    MilestoneApprovedEvent.OutputTuple,
    MilestoneApprovedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneCreated"
  ): TypedContractEvent<
    MilestoneCreatedEvent.InputTuple,
    MilestoneCreatedEvent.OutputTuple,
    MilestoneCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneRejected"
  ): TypedContractEvent<
    MilestoneRejectedEvent.InputTuple,
    MilestoneRejectedEvent.OutputTuple,
    MilestoneRejectedEvent.OutputObject
  >;
  getEvent(
    key: "ProofSubmitted"
  ): TypedContractEvent<
    ProofSubmittedEvent.InputTuple,
    ProofSubmittedEvent.OutputTuple,
    ProofSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierAdded"
  ): TypedContractEvent<
    VerifierAddedEvent.InputTuple,
    VerifierAddedEvent.OutputTuple,
    VerifierAddedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierRemoved"
  ): TypedContractEvent<
    VerifierRemovedEvent.InputTuple,
    VerifierRemovedEvent.OutputTuple,
    VerifierRemovedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "DonorAdded(address,uint256)": TypedContractEvent<
      DonorAddedEvent.InputTuple,
      DonorAddedEvent.OutputTuple,
      DonorAddedEvent.OutputObject
    >;
    DonorAdded: TypedContractEvent<
      DonorAddedEvent.InputTuple,
      DonorAddedEvent.OutputTuple,
      DonorAddedEvent.OutputObject
    >;

    "MilestoneApproved(uint256,uint256,uint256)": TypedContractEvent<
      MilestoneApprovedEvent.InputTuple,
      MilestoneApprovedEvent.OutputTuple,
      MilestoneApprovedEvent.OutputObject
    >;
    MilestoneApproved: TypedContractEvent<
      MilestoneApprovedEvent.InputTuple,
      MilestoneApprovedEvent.OutputTuple,
      MilestoneApprovedEvent.OutputObject
    >;

    "MilestoneCreated(uint256,string,string,uint256)": TypedContractEvent<
      MilestoneCreatedEvent.InputTuple,
      MilestoneCreatedEvent.OutputTuple,
      MilestoneCreatedEvent.OutputObject
    >;
    MilestoneCreated: TypedContractEvent<
      MilestoneCreatedEvent.InputTuple,
      MilestoneCreatedEvent.OutputTuple,
      MilestoneCreatedEvent.OutputObject
    >;

    "MilestoneRejected(uint256,uint256,uint256)": TypedContractEvent<
      MilestoneRejectedEvent.InputTuple,
      MilestoneRejectedEvent.OutputTuple,
      MilestoneRejectedEvent.OutputObject
    >;
    MilestoneRejected: TypedContractEvent<
      MilestoneRejectedEvent.InputTuple,
      MilestoneRejectedEvent.OutputTuple,
      MilestoneRejectedEvent.OutputObject
    >;

    "ProofSubmitted(uint256,bytes32,bytes32,string,address)": TypedContractEvent<
      ProofSubmittedEvent.InputTuple,
      ProofSubmittedEvent.OutputTuple,
      ProofSubmittedEvent.OutputObject
    >;
    ProofSubmitted: TypedContractEvent<
      ProofSubmittedEvent.InputTuple,
      ProofSubmittedEvent.OutputTuple,
      ProofSubmittedEvent.OutputObject
    >;

    "VerifierAdded(address)": TypedContractEvent<
      VerifierAddedEvent.InputTuple,
      VerifierAddedEvent.OutputTuple,
      VerifierAddedEvent.OutputObject
    >;
    VerifierAdded: TypedContractEvent<
      VerifierAddedEvent.InputTuple,
      VerifierAddedEvent.OutputTuple,
      VerifierAddedEvent.OutputObject
    >;

    "VerifierRemoved(address)": TypedContractEvent<
      VerifierRemovedEvent.InputTuple,
      VerifierRemovedEvent.OutputTuple,
      VerifierRemovedEvent.OutputObject
    >;
    VerifierRemoved: TypedContractEvent<
      VerifierRemovedEvent.InputTuple,
      VerifierRemovedEvent.OutputTuple,
      VerifierRemovedEvent.OutputObject
    >;

    "VoteCast(uint256,address,bool,string)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
