/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TaskEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "backend"
      | "getTaskAudit"
      | "recordAIVerification"
      | "recordDispute"
      | "recordPaymentRelease"
      | "recordTaskAcceptance"
      | "recordTaskCreation"
      | "recordWorkSubmission"
      | "tasks"
      | "verifyImageHash"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AIVerified"
      | "PaymentReleased"
      | "TaskAccepted"
      | "TaskCreated"
      | "TaskDisputed"
      | "WorkSubmitted"
  ): EventFragment;

  encodeFunctionData(functionFragment: "backend", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTaskAudit",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordAIVerification",
    values: [BytesLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "recordDispute",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordPaymentRelease",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordTaskAcceptance",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordTaskCreation",
    values: [BytesLike, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordWorkSubmission",
    values: [BytesLike, string, string]
  ): string;
  encodeFunctionData(functionFragment: "tasks", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "verifyImageHash",
    values: [BytesLike, string, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "backend", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTaskAudit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordAIVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordPaymentRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordTaskAcceptance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordTaskCreation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordWorkSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tasks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyImageHash",
    data: BytesLike
  ): Result;
}

export namespace AIVerifiedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    confidence: BigNumberish,
    approved: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    confidence: bigint,
    approved: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    taskId: string;
    confidence: bigint;
    approved: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentReleasedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    worker: AddressLike,
    amountINR: BigNumberish,
    stripeTransferId: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    worker: string,
    amountINR: bigint,
    stripeTransferId: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    taskId: string;
    worker: string;
    amountINR: bigint;
    stripeTransferId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskAcceptedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    worker: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [taskId: string, worker: string, timestamp: bigint];
  export interface OutputObject {
    taskId: string;
    worker: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCreatedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    client: AddressLike,
    amountINR: BigNumberish,
    stripePaymentIntentId: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    client: string,
    amountINR: bigint,
    stripePaymentIntentId: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    taskId: string;
    client: string;
    amountINR: bigint;
    stripePaymentIntentId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskDisputedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [taskId: string, reason: string, timestamp: bigint];
  export interface OutputObject {
    taskId: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkSubmittedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    beforeImageHash: string,
    afterImageHash: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    beforeImageHash: string,
    afterImageHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    taskId: string;
    beforeImageHash: string;
    afterImageHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TaskEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): TaskEscrow;
  waitForDeployment(): Promise<this>;

  interface: TaskEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  backend: TypedContractMethod<[], [string], "view">;

  getTaskAudit: TypedContractMethod<
    [taskId: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        string,
        string
      ] & {
        client: string;
        worker: string;
        amountINR: bigint;
        status: bigint;
        createdAt: bigint;
        completedAt: bigint;
        beforeImageHash: string;
        afterImageHash: string;
        aiConfidence: bigint;
        stripePaymentIntentId: string;
        stripeTransferId: string;
      }
    ],
    "view"
  >;

  recordAIVerification: TypedContractMethod<
    [taskId: BytesLike, confidence: BigNumberish, approved: boolean],
    [void],
    "nonpayable"
  >;

  recordDispute: TypedContractMethod<
    [taskId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  recordPaymentRelease: TypedContractMethod<
    [taskId: BytesLike, stripeTransferId: string],
    [void],
    "nonpayable"
  >;

  recordTaskAcceptance: TypedContractMethod<
    [taskId: BytesLike, worker: AddressLike],
    [void],
    "nonpayable"
  >;

  recordTaskCreation: TypedContractMethod<
    [
      taskId: BytesLike,
      client: AddressLike,
      amountINR: BigNumberish,
      stripePaymentIntentId: string
    ],
    [void],
    "nonpayable"
  >;

  recordWorkSubmission: TypedContractMethod<
    [taskId: BytesLike, beforeHash: string, afterHash: string],
    [void],
    "nonpayable"
  >;

  tasks: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        string,
        string
      ] & {
        client: string;
        worker: string;
        amountINR: bigint;
        status: bigint;
        createdAt: bigint;
        completedAt: bigint;
        beforeImageHash: string;
        afterImageHash: string;
        aiConfidence: bigint;
        stripePaymentIntentId: string;
        stripeTransferId: string;
      }
    ],
    "view"
  >;

  verifyImageHash: TypedContractMethod<
    [taskId: BytesLike, imageHash: string, isBefore: boolean],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "backend"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTaskAudit"
  ): TypedContractMethod<
    [taskId: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        string,
        string
      ] & {
        client: string;
        worker: string;
        amountINR: bigint;
        status: bigint;
        createdAt: bigint;
        completedAt: bigint;
        beforeImageHash: string;
        afterImageHash: string;
        aiConfidence: bigint;
        stripePaymentIntentId: string;
        stripeTransferId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordAIVerification"
  ): TypedContractMethod<
    [taskId: BytesLike, confidence: BigNumberish, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordDispute"
  ): TypedContractMethod<
    [taskId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordPaymentRelease"
  ): TypedContractMethod<
    [taskId: BytesLike, stripeTransferId: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordTaskAcceptance"
  ): TypedContractMethod<
    [taskId: BytesLike, worker: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordTaskCreation"
  ): TypedContractMethod<
    [
      taskId: BytesLike,
      client: AddressLike,
      amountINR: BigNumberish,
      stripePaymentIntentId: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordWorkSubmission"
  ): TypedContractMethod<
    [taskId: BytesLike, beforeHash: string, afterHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tasks"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        string,
        string
      ] & {
        client: string;
        worker: string;
        amountINR: bigint;
        status: bigint;
        createdAt: bigint;
        completedAt: bigint;
        beforeImageHash: string;
        afterImageHash: string;
        aiConfidence: bigint;
        stripePaymentIntentId: string;
        stripeTransferId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyImageHash"
  ): TypedContractMethod<
    [taskId: BytesLike, imageHash: string, isBefore: boolean],
    [boolean],
    "view"
  >;

  getEvent(
    key: "AIVerified"
  ): TypedContractEvent<
    AIVerifiedEvent.InputTuple,
    AIVerifiedEvent.OutputTuple,
    AIVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentReleased"
  ): TypedContractEvent<
    PaymentReleasedEvent.InputTuple,
    PaymentReleasedEvent.OutputTuple,
    PaymentReleasedEvent.OutputObject
  >;
  getEvent(
    key: "TaskAccepted"
  ): TypedContractEvent<
    TaskAcceptedEvent.InputTuple,
    TaskAcceptedEvent.OutputTuple,
    TaskAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCreated"
  ): TypedContractEvent<
    TaskCreatedEvent.InputTuple,
    TaskCreatedEvent.OutputTuple,
    TaskCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskDisputed"
  ): TypedContractEvent<
    TaskDisputedEvent.InputTuple,
    TaskDisputedEvent.OutputTuple,
    TaskDisputedEvent.OutputObject
  >;
  getEvent(
    key: "WorkSubmitted"
  ): TypedContractEvent<
    WorkSubmittedEvent.InputTuple,
    WorkSubmittedEvent.OutputTuple,
    WorkSubmittedEvent.OutputObject
  >;

  filters: {
    "AIVerified(bytes32,uint8,bool,uint256)": TypedContractEvent<
      AIVerifiedEvent.InputTuple,
      AIVerifiedEvent.OutputTuple,
      AIVerifiedEvent.OutputObject
    >;
    AIVerified: TypedContractEvent<
      AIVerifiedEvent.InputTuple,
      AIVerifiedEvent.OutputTuple,
      AIVerifiedEvent.OutputObject
    >;

    "PaymentReleased(bytes32,address,uint256,string,uint256)": TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;
    PaymentReleased: TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;

    "TaskAccepted(bytes32,address,uint256)": TypedContractEvent<
      TaskAcceptedEvent.InputTuple,
      TaskAcceptedEvent.OutputTuple,
      TaskAcceptedEvent.OutputObject
    >;
    TaskAccepted: TypedContractEvent<
      TaskAcceptedEvent.InputTuple,
      TaskAcceptedEvent.OutputTuple,
      TaskAcceptedEvent.OutputObject
    >;

    "TaskCreated(bytes32,address,uint256,string,uint256)": TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
    TaskCreated: TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;

    "TaskDisputed(bytes32,string,uint256)": TypedContractEvent<
      TaskDisputedEvent.InputTuple,
      TaskDisputedEvent.OutputTuple,
      TaskDisputedEvent.OutputObject
    >;
    TaskDisputed: TypedContractEvent<
      TaskDisputedEvent.InputTuple,
      TaskDisputedEvent.OutputTuple,
      TaskDisputedEvent.OutputObject
    >;

    "WorkSubmitted(bytes32,string,string,uint256)": TypedContractEvent<
      WorkSubmittedEvent.InputTuple,
      WorkSubmittedEvent.OutputTuple,
      WorkSubmittedEvent.OutputObject
    >;
    WorkSubmitted: TypedContractEvent<
      WorkSubmittedEvent.InputTuple,
      WorkSubmittedEvent.OutputTuple,
      WorkSubmittedEvent.OutputObject
    >;
  };
}
